DROP TABLE PRODUCT_TBL;

CREATE TABLE PRODUCT_TBL(
    PRODUCT_BNO NUMBER(10) PRIMARY KEY,
    CATEGORY_CODE VARCHAR2(30) NOT NULL,
    PRODUCT_NAME VARCHAR2(500) NOT NULL,
    PRODUCT_CONTENT VARCHAR2(4000) NOT NULL,
    PRODUCT_PRICE VARCHAR2(100) NOT NULL,
    PRODUCT_STOCK VARCHAR2(100) NOT NULL,
    IMAGEfILENAME VARCHAR2(100),
    WRITEDATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE PRODUCT_BNO_SEQ;
CREATE SEQUENCE PRODUCT_BNO_SEQ;

INSERT INTO PRODUCT_TBL(PRODUCT_BNO,PRODUCT_NAME,PRODUCT_CONTENT,PRODUCT_PRICE,PRODUCT_STOCK,IMAGEfILENAME)
VALUES (PRODUCT_BNO.NEXTVAL,'딸기마카롱','딸기마카롱내용','2000','10');
INSERT INTO PRODUCT_TBL(PRODUCT_BNO,PRODUCT_NAME,PRODUCT_CONTENT,PRODUCT_PRICE,PRODUCT_STOCK,IMAGEfILENAME)
VALUES (PRODUCT_BNO.NEXTVAL,'초코마카롱','초코마카롱내용','1500','18');

SELECT * FROM PRODUCT_TBL;

COMMIT;

--조회수 컬럼추가
ALTER TABLE PRODUCT_TBL ADD VIEW_COUNT NUMBER DEFAULT 0 NOT NULL;

